### ISSUE TITLE
Original images in photo albums are saved and downloaded

### ISSUE THREAD

**Issue by thaliawww-service** [svthalia/concrexit#1017]
In GitLab by @gijshendriksen on Mar 11, 2020, 18:28

### One-sentence description

When downloading a photo album, both the original and downscaled images are downloaded, even though we're not supposed to save the original image.

### Current behaviour / Reproducing the bug

1. Download a photo album
2. Notice the original images are saved and included in the album (`*.JPG`), alongside the downscaled images (`*.jpg`)

### Expected behaviour

1. Download a photo album
2. Only the downscaled images are saved and included

**Comment by se-bastiaan** [comment]
I have been working on this issue, but my file system does not look at the casing of text in a filename. Since a Linux file system is case sensitive and our resized images use the extension `.jpg` while the originals mostly use `.JPG` we have loads of originals on our server now I think.

@pingiun @joren485 could you take a look at this? And any ideas how to solve that?

**Comment by joren485** [comment]
There are albums with only `*.JPG` files, albums with only `*.jpg` files and albums with both.

**Comment by se-bastiaan** [comment]
I think the albums with both the uppercase and lowercase are the ones with the originals, especially if they have the same filename in front of the extension.

**Comment by joren485** [comment]
The originals are a lot bigger than the downscaled images. We could identify them by their size.

**Comment by se-bastiaan** [comment]
I believe this would be the perfect to do that, since there won't be any new photos for a while. And I think we can release it before events start again.
