### ISSUE TITLE
Manually entered usernames not lowercased in registrations

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1073]
### Describe the bug
Manually entered usernames are not lowercased in registrations.

### How to reproduce
Steps to reproduce the behaviour:
1. Create a registration
2. Enter a manual username that is not completely lowercase
3. Complete the registration
4. Try to log-in with the new user
5. It is not possible

### Expected behaviour
The username should have been lowercased, since it is not possible to login with a username that has capitalisaton of any kind.

**Comment by se-bastiaan** [comment]
The issue here is not that someone with a capiital in the username is not able to login. The problem is that this user had a non-lowercase character in the first place.

We have overridden forms to support case insensitive usernames in [user creation](https://github.com/svthalia/concrexit/blob/master/website/members/forms.py#L48), [user modification](https://github.com/svthalia/concrexit/blob/master/website/members/forms.py#L99) and [authentication](https://github.com/svthalia/concrexit/blob/master/website/thaliawebsite/forms.py#L5). We do this by always _lowercasing_ any username.

The username is automatically generated in [the registrations code](https://github.com/svthalia/concrexit/blob/master/website/registrations/services.py#L21). There it is lowercased. 

So the only option left is that the registration had a manually entered username.

**Comment by se-bastiaan** [comment]
I would say this is easy to fix, but it would require an extra test case to prevent this from happening again.
