### ISSUE TITLE
Use CSS variables for dark mode

### ISSUE THREAD

**Issue by se-bastiaan** [svthalia/concrexit#1100]
### Describe the change
Use CSS variables instead of SASS variables for our colour schemes like changing dark mode.

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
https://sparanoid.com/note/css-variables-guide/
https://engineering.fb.com/web/facebook-redesign/

### Motivation
It would mean less files to maintain and 77KB less to load on first page visit.

### Current implementation
Currently we have two CSS files that are compiled from our SASS code, one for light and one for dark mode. This results in the user's browser loading two files. Since they are compiled and compressed they are just 77KB. But there are still two files and the current configuration is quite complex for first time SASS users. 

### Suggested implementation
Use the CSS variables and have only one single 'main' SASS file that switches between the colour variables. The urls above should give a good idea on how this works.

**Comment by chrysillala** [comment]
Hi, I would like to work on this issue as part of Hacktoberfest. Could you please assign and guide me? Thanks!

**Comment by pingiun** [comment]
Hey @chrysillala, thanks for checking this out. The main css files are [main.css](https://github.com/svthalia/concrexit/blob/f955c402c5a6e65639652d4d5c42002126f4c382/website/thaliawebsite/static/css/main.scss) and [main-dark.css](https://github.com/svthalia/concrexit/blob/f955c402c5a6e65639652d4d5c42002126f4c382/website/thaliawebsite/static/css/main-dark.scss)

As you can see, these use scss imports which select the two files with scss variables. The actual dark/light mode is selected [in html](https://github.com/svthalia/concrexit/blob/f955c402c5a6e65639652d4d5c42002126f4c382/website/thaliawebsite/templates/base.html#L39)

Instead of these scss variables we would like to use CSS variables, as explained in the issue

**Comment by chrysillala** [comment]
Hi @se-bastiaan, kindly check my PR here https://github.com/svthalia/concrexit/pull/1349
Thanks!
