### ISSUE TITLE
Statistics page: 'current number of Thalians' does not count unique members

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1181]
I haven't looked at the code to verify this, but I think I'm pretty certain. 

### Describe the bug
Statistics page: 'current number of Thalians' does not count unique members, but only the number of memberships. Hence, if somebody changes from member to benefactor, or member to honorary member, the count is incorrect.

### How to reproduce
Check statistics page

### Expected behaviour
Count the number of unique members of all Thalians.

### Additional context
The count currently says 638 Thalians, but according to my own count, it should be 637 if I did not make mistakes

**Comment by se-bastiaan** [comment]
The count uses the following exploded query:
```
Member.objects
    .exclude(membership=None)
    .filter(Q(membership__until__isnull=True) | Q(membership__until__gt=timezone.now().date()))
    .distinct()
    .count()
```
being `Member.current_members.count()` in the codebase.

Or: the distinct count of all members that have a membership of which the end date is empty or lies before today.

Since I am not sure what the query for the export was I would say that this one is correct.

-- 
However after typing this I am not 100% sure how this works because `membership` is not a field of `Member` directly. So to know where it comes from I would have to look further into the codebase.

**Comment by se-bastiaan** [comment]
https://github.com/svthalia/concrexit/blame/c7030ca1db9669ce9b178dca3bd55e18b1ab7cea/website/members/models.py#L33
https://github.com/svthalia/concrexit/commit/6aab5288824bbb171aa58b0636a240e6232b977d#diff-5457231243cd6e1b81dc3dc3d517c3b8R38
https://github.com/svthalia/concrexit/commit/3412a64e0cc3b3761c562aa1761efe000d5f4e77

goes back to

https://github.com/svthalia/concrexit/commit/41d4a1de6c00c5711d0db77a78e592bcaa0a4051#diff-5457231243cd6e1b81dc3dc3d517c3b8R18

**Comment by se-bastiaan** [comment]
We found that the export and the pages were from different times and thus the number of members increased since we count all future members as well.
