### ISSUE TITLE
Remove Dutch translation from the website

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#1200]
### Describe the change
The new policy of the board is that the website only has to support English, we should remove all the Dutch translations

To do:
- [x] Remove Dutch from settings.LANGUAGES (#1202)
- [x] Remove po and mo files (#1202)
- [ ] Remove mutilingualfield util functions and class

Remove multilingual field and the references to _en attributes from the following apps:
- [x] activemembers (#1216)
- [x] announcements (#1217)
- [x] documents (#1272, #1296)
- [x] education (#1273)
- [x] events
- [x] mailinglists
- [x] members
- [ ] merchandise?
- [ ] newsletters
- [x] partners
- [x] pizzas
- [ ] push notifications?
- [x] registrations
- [x] singlepages?
- [x] thabloid?

**Comment by se-bastiaan** [comment]
Maybe what I wrote in the PR should also be here:

> Even though I understand that it may be easy to change the Dutch fields to be optional I do not see why we cannot just remove the complete Dutch functionality at once. I'm not really a fan of a half translated website just because we want to keep some Dutch explanations that are not required.
> 
> Technically we only need to keep the legal documents in Dutch but I'm not sure if that is connected to the translations in django.

You say
> The board should create other issues on how this policy should be implemented further.

The thing the board wanted is 'English-only' website I believe. That is fine, but this seems to be a half-hearted approach to solve something nobody has asked us to do yet. A partially English-Dutch website is a no-go in my opinion.

**Comment by pingiun** [comment]
The main thing I am concerned about is old event texts that are only available in Dutch because the English version only says something like "this event is in Dutch, read the Dutch text for more information". I don't think it's a good idea to throw these old texts away.

**Comment by se-bastiaan** [comment]
But what do we want to do with those texts? I think everything from at least the past two years has been in both Dutch and English. And I know that events that were Dutch-only had that as start of the event text, the rest was in Dutch even for the English users. Mostly because people complained that they didn't want to switch languages just because they as Dutchies used the English website.

**Comment by pingiun** [comment]
You make a good point. So do you think it would be fine to just throw away all the translations we have?

**Comment by mariesophiesimon** [comment]
Sebas noted very correctly that we did want Dutch fields to be optional, but everything should be English. The events that are only available in Dutch, like lectures from the Defense or so, we are also still a little torn about. On the one hand it would be weird for members to describe a Dutch event in English, however we do want to avoid inconsistency on the website. There were different suggestions on how to solve this or how to make a compromise, we are also still open for input from you guys.

**Comment by se-bastiaan** [comment]
As I already mentioned to @pingiun directly I think it is perfectly fine to remove all the translation data that we have for old events etc. Because:

> Digital is mainly garbage. 90% of data is never accessed again 90 days after it is first stored. 80% of downloaded apps are never used again after 90 days. 90% of data has been created in the last two years. Over the years, we found that we had to delete 90% of a typical website to make it useful. Even the information that is used is usually full of garbage.
https://gerrymcgovern.com/digital-is-garbage/

What we should not do is remove the Dutch summaries and exams (since there are a lot in our database) or the Dutch association documents (since those are the official ones). Everything else can be English-only.

@pingiun already made the first changes to be able to switch to English-only for the most part, we then have to remove all the functionality that added the translation possibilities later. We cannot say when we will be able to release this.

As for events that are only in Dutch I would just add 'This event is in Dutch' to the top of the description. You will never be able to force the partners to give you the text in English and this is something we have to live with. I believe this is something that was already done that way.

**Comment by se-bastiaan** [comment]
@pingiun Maybe it is nice to have a bullet point todo list at the start of this issue to mark what we need to do to close this issue?

**Comment by pingiun** [comment]
Good idea, I will collect a list

**Comment by JobDoesburg** [comment]
- [ ] Remove communication preference property `@property def language` (https://github.com/svthalia/concrexit/blob/8320b4fd22b5d320e8b8e2cef5888fd24071d6f4/website/members/models/profile.py#L213 and https://github.com/svthalia/concrexit/blob/8320b4fd22b5d320e8b8e2cef5888fd24071d6f4/website/registrations/models.py#L195)
