### ISSUE TITLE
Switch production to NixOS

### ISSUE THREAD

**Issue by wdoeland** [svthalia/concrexit#1561]
### Describe the change
Currently we are running the production version of Concrexit on a Ubuntu server using docker compose and ansible. Our staging environment has been running through Nix(OS) for the past few months and we believe it is stable. We want to switch our production server to running through NixOS. We will not be running green/blue deployments at this time. 

This issue describes what should still be done:

### Checklist before switching
- [x] Fix #1556 
- [ ] create a new server for production on AWS and set up NixOS with our config (via terraform?)
- [ ] Communicate to members about downtime
- [x] Create EBS disks (psql, media)
- [x] Create Terraform scripts

### Checklist while switching
- [ ] take the current server offline by stopping nginx
- [ ] make a backup of all data
- [ ] migrate database
- [ ] migrate media
- [ ] point the elastic IP to the new EC2 production instance
- [ ] test the new server extensively

### Checklist after switching
- [ ] terminate the old server (I think it'd be nice if we still kept it alive for a few weeks)

**Comment by se-bastiaan** [comment]
- Does NixOS already have a backup solution implemented? If yes, is it compatible with the old backups? 
- This requires communication to our members since it will result in downtime, so we should plan this ahead.
- Isn't it possible to point the elastic IP to the new server instead of changing the DNS records?
- Isn't it possbible to stop the current server and just keep the storage drives active for a few weeks? In any case, it does not make sense to me to keep something alive that you will not be able to switch back to.

**Comment by pingiun** [comment]
> Does NixOS already have a backup solution implemented? If yes, is it compatible with the old backups?
The only thing we would have is EC2 disk snapshots. I think it would be nice to at least have database backups too. 

> Isn't it possible to point the elastic IP to the new server instead of changing the DNS records?
Good idea, I think we should do this

> Isn't it possbible to stop the current server and just keep the storage drives active for a few weeks?
I think the production snapshots are stored for a month regardless. I think keeping the server alive for weeks would be unnecessary indeed, although keeping it alive for just a small while is nice just to be able to switch back if all things go wrong

**Comment by pingiun** [comment]
I think it might be nice to store all the media (photos etc) on a separate EBS disk. This is easier than storing it on S3 but would still give some benefit because it seperates a stateful element from a server that is generally stateless (because of Nix). And maybe it allows us to resize the disk easier? I'm not sure about that though

**Comment by pingiun** [comment]
Creating the separate EBS disk for media would also allow for easier migration, as we could just attach it to the old server, migrate everything and then attach it to the new server

**Comment by se-bastiaan** [comment]
I do agree that we should have more than just EC2 snapshots. Those are not restorable on anything else than EC2.

How does this affect the review environments?

**Comment by wdoeland** [comment]
>     * Isn't it possible to point the elastic IP to the new server instead of changing the DNS records?

Yes this would also be possible but I thought it would be cleaner to switch it through our DNS records.

**Comment by pingiun** [comment]
> How does this affect the review environments?

It doesn't. Review environments should also be done using Nix, so that we can drop the docker config

**Comment by Luca-Castelnuovo** [comment]
>  Communicate to members about downtime

Dear Thalia People,

You can expect some downtime on the thalia.nu site.
We will be transferring to a new server system, for those interested take a look at: https://github.com/svthalia/concrexit/issues/1561.

Thank you for understanding.
We will send an update when the migration is complete or more downtime is to be expected.

Kind regards,
The Technicie
