### ISSUE TITLE
Vacancies in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1642]
### Describe the solution you'd like
API v2 endpoints for partners and vacancies.

### Motivation
It might be interesting to also show the partners and vacancies in the app some day. If we want to do that, we'll need them in the api. I suppose this might be something to discuss with the commissioner of external affairs.

### Describe alternatives you've considered
Not doing it. If we don't want it in the app, we don't need it in the api.

**Comment by se-bastiaan** [comment]
Can you please use the issue template?

**Comment by se-bastiaan** [comment]
@pingiun Do we maybe want to ask the board if this is a good idea?

**Comment by pingiun** [comment]
I think it's a good idea to ask the commissioner of external affairs whether partners have ever asked for this. I don't think they have because the partners won't see the app at all (except when they become a members, which maybe has happened once). But maybe the commissioner can inquire whether partners would be interested in this. Either way, I will send an email to Michiel.

**Comment by DeD1rk** [comment]
Yes I think it would in any case be very nice for partners, as it probably more than doubles their visibility. If desirable (though it might be better to just 'give' it as an extra to partners, we could also add a field `display_in_app` or something, so it can be chosen per partner/vacancy.

**Comment by se-bastiaan** [comment]
Given that we already exposed partners in API v1 they have also been exposed in v2. Nothing about vacancies tho.

**Comment by pingiun** [comment]
@wdoeland
