### ISSUE TITLE
Merchandise products in sales productlists

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1657]
### Is your feature request related to a problem? Please describe.
With the new `sales` app, it would be nice to have the possibility (for the board) to also do merchandise sales via this system.

### Describe the solution you'd like
Make a `sales.ProductList` of `merchandise.Item`s 

### Motivation
Merchandise products are also products.

### Additional context
- Perhaps, we want to make `MerchandiseItem`s actually extend `Product`s (so the `sales` app doesn't need to change too much). 
- We should think about how to go with different sizes. For example, maybe we want to keep what we currently have as `MerchandiseProduct`s and then have multiple `MerchandiseVariant`s for different sizes, that are the actual products. This way, we can display a single merchandise product but actually have multiple versions for it.
- We should think about how this would work with product lists and prices.

**Comment by se-bastiaan** [comment]
Why can't this just be a regular product list? Do we really need to keep track of the size?

**Comment by JobDoesburg** [comment]
> Why can't this just be a regular product list?
It feels weird to have this data in the website twice, both in a product list and in the merchandise app. I think we can couple this.

> Do we really need to keep track of the size?
Yes, for the bookkeeping.

**Comment by se-bastiaan** [comment]
I thought that the sales app was just for the payments, not for the bookkeeping. What I think you are suggesting is building an inventory system.

Look, I get the idea. But coupling the simplest app that we have just to make it possible to do something without the changes makes me feel uncomfortable. I know I always take the conservative "we don't really need this" stance. But this could be solved by creating a product list where all the sizes are a different product, which they essentially are.

That still leaves me wondering if the sales app really needs to know the size, because the price does not change based on that value. The idea of the sales app was to make it possible for Thalia Pay to be used at borrels. Put it in an easy to use formfactor.

**Comment by JobDoesburg** [comment]
> What I think you are suggesting is building an inventory system.

No that's not my point (yet - I'll wait for you to leave the Technicie before I'm building that, for my own safety).


> But this could be solved by creating a product list where all the sizes are a different product, which they essentially are. Or by adding the possibility to add varieties to a product. And no couple it at all.

If that's what we're building, then the only coupling we would introduce in the merchandise app is a single ForeignKey. For me it just feels the same as Events and photo Albums. 


> That still leaves me wondering if the sales app really needs to know the size, because the price does not change based on that value. 

If we're not storing that information, then there's no point in using this whole app at all, as it would require the board to keep a separate spreadsheet with this information

**Comment by JobDoesburg** [comment]
Will be implemented in #3464
