### ISSUE TITLE
Immutable payables

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#1766]
### Describe the change
A common problem, also in our current codebase, is that we often want to prevent changing payables when they are already paid. Think of Food/Sales orders. Right now there is no good way to fix this fundamentally. Sales orders only prevent saving when the amount of the payment and the order don't match (but doesn't update the description, for example). Food orders since #1765 only does the check in the view.

A way to solve this fundamentally would be the following:
- Payables get an additional boolean property `immutable_after_payment` that defaults to False, but can be enabled for models where we want to apply this
- The payments app implements a pre_save_signal on payable models that raises an exception if a model that is `immutable_after_payment` and has a payment is tried to be saved. (Or it tries to delete the payment and will raise the exception when that is not possible anymore - for example because the payment has already been processed).

### Motivation
This is a problem that applies to all payables and could be a generic fix.

### Current implementation
Messy, not really 

### Suggested implementation
See above

**Comment by se-bastiaan** [comment]
It took me a while to understand what the issue is about, your explanation of the problem is really unclear. 
> we often want to prevent changing payables
But why do you want to do that? This is not directly mentioned in the current description.

From what I understand this issue is about the payables that can be changed while already having a payment. Changing the payable does not change the existing payment, which will mean that the values will not be up-to-date.

This is the case when the title of an event changes, or maybe the type of pizza in a food order. You could probably name some of the other cases as well. In the food order case we already check if this may cause problems and block updates, but there are cases where these checks are currently not sufficient.

Therefore we would like to implement some sort of immutability for the models that are registered as a Payable.

---

In my opinion making the models that are registered as a payable immutable makes a lot of sense, I would no implement this as an option but force it for all of them. I am not sure if a signal will correctly block saving the models, have never tried that before.

**Comment by JobDoesburg** [comment]
>  I am not sure if a signal will correctly block saving the models, have never tried that before.
Yes it does, at least for individual save's. Not for bulk creates though.
