### ISSUE TITLE
Payment not visible

### ISSUE THREAD

**Issue by Jorritboer** [svthalia/concrexit#1777]
### Describe the bug
In the administration page of an event for which you have to pay the payment method is invisible on some browsers. Clicking on the payment does still reveal the menu with the options. See the screenshots below.

### How to reproduce
Steps to reproduce the behaviour:
1. Go to the admin page of an event on Chrome or Firefox.
2. See the payment method

### Screenshots
![image](https://user-images.githubusercontent.com/45050184/123062689-0c3e3980-d40d-11eb-8ba6-56e248feeadc.png)
![image](https://user-images.githubusercontent.com/45050184/123062915-3b54ab00-d40d-11eb-9874-5b53f6a032c6.png)
Expected:
![image](https://user-images.githubusercontent.com/45050184/123063229-81aa0a00-d40d-11eb-9701-0bce25fe504c.png)

### Additional context
I don't have the problem on Safari, I do have it on Chrome and I heard it's also a problem on Firefox.
Maybe it has something to do with the darkmode. I also don't understand why dark mode doesn't seem to activate on Chrome for me.

**Comment by JobDoesburg** [comment]
Safari 14 light mode
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7915741/123065299-52949800-d40f-11eb-9ccf-7432f4fd50ae.png">

Chrome 91.0.4472.114 on macOS dark mode
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7915741/123065728-b7e88900-d40f-11eb-9b01-7586c9611504.png">

Chrome 91.0.4472.114 on macOS light mode
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7915741/123065861-d484c100-d40f-11eb-8d37-e4e4d2968b41.png">

Firefox 88.0.1 on macOS dark mode
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7915741/123066207-2299c480-d410-11eb-9a95-d07b0b2bf12b.png">

Firefox 88.0.1 on macOS light mode
<img width="386" alt="image" src="https://user-images.githubusercontent.com/7915741/123066296-36ddc180-d410-11eb-8946-8ed0768c25fa.png">

--

The problem is that in light mode, the text color is still white, while it should become black. Also, the success/fail colors we're using are a bit pastel in light mode, but I don't think that's a real problem if we change the text color.

I cannot reproduce the field being totally missing. @Jorritboer just to be sure, did you delete your caches. The styling could very well be in cache still causing some problems. This might also be the reason why chrome doesn't activate dark mode for you (or perhaps you have a plugin preventing it).

@pingiun I think this is something we might want to hotfix next week (although there are no events coming up so we're not too much in a hurry)

**Comment by Jorritboer** [comment]
Ah yes the caches was the problem for it totally disappearing (I really should have checked this oops). 
Then the issue just becomes changing the text (and possibly the success/fail) color in light mode.
