### ISSUE TITLE
Add tpay_allowed to FoodOrder or FoodEvent in API v2

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#1784]
### Describe the solution you'd like
Adding the field to the FoodEvent and/or FoodOrder serializer.

### Motivation
Currently you can only see whether an order can be paid with Thalia Pay (whether to show a tpay button) by requesting the payable through the payments api.

**Comment by se-bastiaan** [comment]
You are supposed to request the payable using the Payments API. Events does not have this information either. This was a deliberate choice.

**Comment by DeD1rk** [comment]
tpay_allowed is a property of the FoodEvent though, so isn't it weird (and inefficient) to only return it for the payable? I guess it does make it possible to specify tpay_allowed per order this way without many changes, but it would add an api request only for that property.

**Comment by DeD1rk** [comment]
In fact, the payments API forbids GETting a payable that cannot be paid with tpay, so requesting that for the orders would be bad. I suppose the payments API should allow GETs to non-tpay payables (or otherwise at least leave out the tpay_allowed property that is guaranteed to be true.

**Comment by DeD1rk** [comment]
@se-bastiaan I see the point of requesting the payable to see `tpay_allowed`, but the payments API does not (yet) really allow this, and although it makes sense (especially taking it from the payable on conrexit) on an app it would cause some annoying and useless delays. E.g. if you have to get the information from the payable for food orders, then:

- You order, the order shows up, and a while later the payment button appears. In the button appearing is a disturbing visual event, and since the payment button should not be shown when tpay is not allowed, the loading cannot be made less explicit than popping in (or out) a button, shifting other elements on the screen.
- Or you order, the order takes a little longer to show up, since an additional request needs to be made.

In both cases, it hurts the user experience for only a gain in uniformity of the code. Simply adding the `tpay_allowed` properties of (food)events does not have these disadvantages, and I would say are even more in line with the idea of a rest api: `tpay_allowed` is a property of a (food)event, so it only makes sense to include it in the serializer.

If you do insist on using only the payments api, that would be nice to know that for sure soon, since I'll then have to make some decisions and boilerplate around getting the payable. If adding to the (food)event serializers is acceptable, I'll just make a simple PR for that and then I can finish up the TPay thingies in the app.

**Comment by se-bastiaan** [comment]
> @se-bastiaan I see the point of requesting the payable to see `tpay_allowed`, but the payments API does not (yet) really allow this

I am not sure what you mean by that it is not possible yet? The tpay_allowed property from the payable determines if you even _can_ get the payable. You will get a 403 in any of the following cases:

- The payable cannot be paid using Thalia Pay
- The user connected to the payable is not the current user

This means that you can request the payable information and if you get no 200 you cannot use it. If you get a response it contains the information you may need.

> , and although it makes sense (especially taking it from the payable on conrexit) on an app it would cause some annoying and useless delays. E.g. if you have to get the information from the payable for food orders, then:
> 
>     * You order, the order shows up, and a while later the payment button appears. In the button appearing is a disturbing visual event, and since the payment button should not be shown when tpay is not allowed, the loading cannot be made less explicit than popping in (or out) a button, shifting other elements on the screen.
> 
>     * Or you order, the order takes a little longer to show up, since an additional request needs to be made.
> 
> 
> In both cases, it hurts the user experience for only a gain in uniformity of the code. Simply adding the `tpay_allowed` properties of (food)events does not have these disadvantages, and I would say are even more in line with the idea of a rest api: `tpay_allowed` is a property of a (food)event, so it only makes sense to include it in the serializer.
> 
> If you do insist on using only the payments api, that would be nice to know that for sure soon, since I'll then have to make some decisions and boilerplate around getting the payable. If adding to the (food)event serializers is acceptable, I'll just make a simple PR for that and then I can finish up the TPay thingies in the app.

Imo the situations you sketch are not all that is possible. The responses from our server are not super large and we use HTTP 2. I think that the overhead of doing an extra HTTP request before showing any information at all adds a negligible delay.

The property tpay_allowed on an event only exists for the payable to use and it does not say everything. It is used in the payable to determine if Thalia Pay is allowed for the payment. And the implementation of a payable can easily contain more than just the property of the event. Thus if the event property is `true` you still have to check the payable and call the API, since that's ultimately where you get the information if Thalia Pay can be used.

**Comment by DeD1rk** [comment]
> You will get a 403 in any of the following cases:

I noticed that. The payable serializer includes `tpay_allowed` though, which implies that that could also be false, and getting 403 as a response when in fact nothing is wrong is bad practice (4xx codes are meant to indicate errors, not properties of the requested entity). 
In the current implementation the tpay_allowed of the payables only depends on their (food)event, and since I can't think of any reason for it to depend on more than that (at least in a way such that we don't want to show any button at all) I think probing for status codes is more 'bad' than relying on the current behaviour of the payables, especially as it's not critical to hide the button without an app update when some hypothetical new functionality is added. But for now I will then just do a request to the payable as well whenever an order/registration changes.

**Comment by JobDoesburg** [comment]
_Job joins the room_

I think you both have a point. The purist in me thinks that anything payment-related should be in the payments app, including the decision whether Thalia Pay is allowed. You definitely wouldn't want to fully rely on it, in cases where (for example) Thalia Pay is allowed for a pizza event, but something in `payments` prevents you from actually using it.

But I also see the point Dirk makes that `tpay_allowed` can be seen as just a property of the event itself. It is a checkbox in the FoodEventAdmin too, so that's a strong argument in favor of adding it to the API (considering you could write to it as well). 

My (weak) opinion is to do add the field to the `FoodEventSerializer`. However, the field there should (of course) **not** be the full reason why the button is shown or not. The value there is the property of the **whole** event and does not say anything about whether the individual users can actually use it. If everything is alright, it of course shouldn't be possible to pay with Thalia Pay if the event itself says it's not allowed, but note that it **is** possible to have completed Thalia Pay payments in an event where `tpay_allowed=False` because the value has changed over time and only says something about **new** payments. Also note that people can be blacklisted from using Thalia Pay. 


Another thing could be to add a nested PayableSerializer to the FoodEventSerializer, btw (but I don't really like that I think)




> I suppose the payments API should allow GETs to non-tpay payables (or otherwise at least leave out the tpay_allowed property that is guaranteed to be true.

I agree with this.

**Comment by se-bastiaan** [comment]
If we add the property to FoodEventSerializer it should also be on the EventSerializer.

Adding the PayableSerializer really sounds like a bad idea given that you need a shitload of code for that. 

Anyways, I just realised that the user's `tpay_enabled` and `tpay_allowed` are not checked when the payable is retrieved, even though this is an entity that the user should not have access to imo. Which is the only reason it throws a 403. And I am not entirely sure why we added the `tpay_allowed` property to the serializer. Probably because we forgot that it makes no sense because the user does not have access to the entity is that value is `False`.

I am fine with adding the property, but checking if there even is access is still important. And we need to add checks on the above to make it completely correct, because it currently does not check that until it reaches `create_payment`.

**Comment by DeD1rk** [comment]
I've already implemented it without the property, so I'll close this for now.
