### ISSUE TITLE
Membership since displaying wrong date

### ISSUE THREAD

**Issue by mark-boute** [svthalia/concrexit#1929]
### Describe the bug
Some members their membership type displays the wrong membership since.
Stating a later year's membership than their first membership (my account displayed 01-09-2020, whilst I have been a member since 01-09-2019 (board fixed this)).

### How to reproduce
Steps to reproduce the behaviour:
1. Go to an account with a wrongly listed membership (e.g. Dirk's https://thalia.nu/members/profile/1902)
2. Scroll down to 'Personal Information'
4. See error in Membership type

### Expected behaviour
The first membership should be displayed

### Screenshots
![image](https://user-images.githubusercontent.com/33718602/133599972-a59205b5-66e3-4119-a270-55e10e92b54e.png)

### Additional context
Probable error caused in the rendering template 
https://github.com/svthalia/concrexit/blob/f1cf6819c67cdef916ea9a69e2d12353893fd8f1/website/members/templates/members/user/profile.html#L43
latest_membership should probably be a reference to the first membership instead.

**Comment by se-bastiaan** [comment]
@mark-boute How did the board fix this? They should not be able to fix this technically. They're not really meant to touch the start date of your membership.


The solution is not really to use the first membership. That membership may have a different type (member) than the membership you currently have (benefactor) if you were once a student and you now still support Thalia. Or the status changed from regular member to honorary member. Because that last thing is what this feature was meant for https://github.com/svthalia/concrexit/issues/1155

**Comment by mark-boute** [comment]
@se-bastiaan I changed my yearly membership to a study membership last intro.
So I only have one membership, for which the starting date was wrong.

Maybe the full solution to prevent this would require a bit more depth.
E.g. check for the first date since of current type instead of just the first date since for current/latest membership

**Comment by se-bastiaan** [comment]
> @se-bastiaan I changed my yearly membership to a study membership last intro.
> So I only have one membership, for which the starting date was wrong.

That depends, if your yearly membership was updated to study membership and that changed the start date then there is a problem in the registrations app that changes the start date, which should not happen in the 'upgrade' (you got a discount) case. That is explained in the [docs](https://thalia-documentation.s3.amazonaws.com/master/registrations.html) for that app.

If you didn't upgrade the existing membership but got a new one then that date was correct and the changes to the administration are wrong. Which would mean that you would have had two memberships:
- 01-09-2019 until 31-09-2020
- 01-09-2020 until None

So the question here is: what happened there? Because it sounds like they either not have 'fixed' this, or something else went wrong last year with your upgrade.

**Comment by mark-boute** [comment]
My Membership history:

I payed €7,50 for 01-09-2019 until 31-08-2020
01-09-2019 until 31-08-2020 expired.
I renewed by paying €7,50, 01-09-2020 until 31-08-2021 was created
I upgraded 01-09-2020 until 31-08-2021 to a Study Membership by paying €22,50
01-09-2020 until 31-08-2021 changed to 01-09-2020 until None

During the first week I noticed my profile showed I was a member since 01-09-2020, whilst I have been a member since 01-09-2019. I sent the board an e-mail asking for them to correct this, which they did.

01-09-2019 until 31-08-2020 was removed.
01-09-2020 until None was changed
01-09-2019 until None was my Membership status until 5 minutes ago.
5 minutes ago I made Walter roll-back the changes to:

01-09-2019 until 31-08-2020
01-09-2020 until None

Because otherwise the budget would be out of balance by +€7,50
