### ISSUE TITLE
Remove weird ghostscript background processing hack

### ISSUE THREAD

**Issue by pingiun** [svthalia/concrexit#2018]
### Describe the change
I don't think it's a good idea to start a thread to run a ghostscript process in the background. Usually we just use cron for background jobs, and I think that could be applicable here too.

https://github.com/svthalia/concrexit/blob/d62d06460760c0f0c0c3d6382b4db927c9314fb5/website/thabloid/models.py#L141

### Motivation
It seems error prone

### Current implementation
A wrapper around subprocess is used to run ghostscript in the background.

### Suggested implementation
Use a cronjob or a background job runner

**Comment by se-bastiaan** [comment]
I personally think your motivation needs some work, because you can hardly say that it 'seems' error prone when it has been working perfectly fine since March 2018. That's contradictory.

Sure, maybe it is not the cleanest or easiest solution because it is creating a thread and running ghostscript in a thread within uwsgi. But the background processing has been part of concrexit since the start. Mostly because it is hard to convert a pdf to an image in any other way.

Removing the processing of the PDF at this moment will give you a problem: the Thabloid will not be available to open for users visiting this page until the cronjob has finished.

We once had the idea of using Celery for this kind of background queue work, but that didn't work out like we had hoped.
