### ISSUE TITLE
Investigate GitHub's auto-generated release-notes

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2033]
### Describe the change
Investigate GitHub's auto-generated release-notes

### Motivation
GitHub implements it probably in a nicer way than we do with our GitHub action

### Current implementation
A GitHub action

### Suggested implementation
Use GitHub's built-in functionality

**Comment by se-bastiaan** [comment]
Githubs auto release notes are a bit less customisable than the [release drafter action](https://github.com/release-drafter/release-drafter) that we use now.

<img width="265" alt="Screenshot 2021-12-07 at 20 37 02" src="https://user-images.githubusercontent.com/1799914/145094769-e2ba1f2b-e089-4953-8933-f212340f42f2.png">

for now I personally think that the current action is better since it allows for more configurability, but in the future the GitHub functionality may be similar.

**Comment by pingiun** [comment]
The Github Action we have now works well
