### ISSUE TITLE
Add a caption information field to event creation

### ISSUE THREAD

**Issue by Komkommer123** [svthalia/concrexit#2056]
### Is your feature request related to a problem? Please describe.
Posting on Instagram with 20 lines of text is usually not that engaging. The newsletter descriptions are quite long.

### Describe the solution you'd like
As of now you make a title and a (longer) description for an event. The idea is to add a middle ground ,a caption of 2 to 3 sentences. This would be just another text field in between the other event information fields.

### Motivation
This is important to make both the newsletter event descriptions shorter and to allow for more effective promotion on social media.

**Comment by se-bastiaan** [comment]
Imo this is something that does not belong in the events package of concrexit. Since it is not used to improve the events functionality of concrexit itself. If you want a shorter description for the newsletter you can simply change the newsletter and enter a different text there. It's not as if the newsletters are automatically created. The auto-filled texts can still be changed by the editor. This sounds a bit like the human factor here is ignored tho. When the text of an event is too long for a newsletter that means it is generally also too long for a webpage. 

I am not entirely sure why adding the text to concrexit makes promotion on social media more effective. You need to have an image for social media too. Sounds like it would be better to put those things in a single page. Like a spreadsheet or folders in Google Drive.

**Comment by DeD1rk** [comment]
This could also be used to make the event cards (on landing page as well as in the app) more useful and attractive.
