### ISSUE TITLE
Notification when moving from queue to participants list

### ISSUE THREAD

**Issue by elanto-dev** [svthalia/concrexit#2265]
### Describe the bug
When number of spots was increased and participants move from queue to participants list, they do not get notification. The system works fine in case of cancellation.

### How to reproduce
Steps to reproduce the behaviour:
1. Create event 
2. Participants are added to the participants list and queue 
3. Number of places is increased
4. People in queue move to participants list
5. Notification about it not sent

### Expected behaviour
Thalia member should receive a notification email about their participation in event.

**Comment by se-bastiaan** [comment]
I have a deja vu. I think we had this issue before. And I remember something about implementation a manual warning that said something along the lines of 'no email is sent'. Moreover, I thought we actually did that.

Mostly because sending an email is quite a 'destructive' operation, you could possible send an email to a full queue even and then find out the number was a mistake. And then you cannot go back. Adding warnings _before_ saving may possibly be an option since Django changed some stuff with the forms in the admin.

**Comment by se-bastiaan** [comment]
`self.message_user` in the admin.py file for the events should work and then we could show a warning like this:
<img width="901" alt="Screenshot 2022-03-30 at 20 10 15" src="https://user-images.githubusercontent.com/1799914/160902902-86e691c4-0d12-4b51-b2e1-c7271295186d.png">

I think we never implemented this and only talked about it.
