### ISSUE TITLE
Use event slug instead of pk in urls

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2308]
### Is your feature request related to a problem? Please describe.
Our event urls (that we share quite often) are pretty ugly (`https://thalia.nu/events/123`). I think it would be nice to have a different url format, like `https://thalia.nu/events/orientationbbq-2022` or  `https://thalia.nu/events/2022/orientationbbq` something.

### Describe the solution you'd like
Add a slug field to events, add url patterns for this.

### Motivation
Nicer urls (that don't necessarily leak when they were created).

### Describe alternatives you've considered
Not doing it

**Comment by se-bastiaan** [comment]
This needs a fallback for event ids stil probablyl, because we use this in a lot of places


I like a /year/month/event-name format personally

**Comment by JobDoesburg** [comment]
> This needs a fallback for event ids stil probablyl, because we use this in a lot of places
I agree, I propose a RedirectView for the pk-based urls

> I like a /year/month/event-name format personally
Only thing is that we need to account for events that change event date. But that's something we can figure out

**Comment by se-bastiaan** [comment]
ah yes, that makes it infinitely more complex to have such a url

**Comment by DeD1rk** [comment]
Wit `/year/month/event-name` urls I would also expect there to be `/year/month` and perhaps `/year` list views, which I don't think we want to implement. (and it creates some overlap with the old `/event-pk` urls that we want to keep. So I would personally prefer a `/event-name-year` url, which can perhaps be overridden as in albums. 
In the normal case where just a year suffix is sufficient `diner-rouler-2022` that works nicely, and shouldn't cause too much of a problem if dates change (only if it's moved to another year which should be rare, and in that case people won't try to use the same url again). Any more complex cases can then be handled by overriding the slug (could be limited to adding a suffix, or allow anything so that the year can even be left out).

**Comment by se-bastiaan** [comment]
Yes I think you're right, that's the best option probably.
