### ISSUE TITLE
OAuth endpoint for member data

### ISSUE THREAD

**Issue by MeItsLars** [svthalia/concrexit#2565]
### Is your feature request related to a problem? Please describe.
For the Thabloidcie, I'm working on a script that can generate sticker sheets containing member names and addresses.

### Describe the solution you'd like
I would like an OAuth API endpoint to receive (at least) the **names and addresses** of members, benefactors and honorary members that want to receive the Thabloid. Optionally, you can also send the complete member profiles and let my application handle the filtering.

### Motivation
Right now, the board downloads member files and sends these files in .csv format to Thabloidcie members. This leaves huge files of member data laying around on the computers of various members of the Thabloidcie. To prevent this, this would be a nice solution.

### Describe alternatives you've considered
The only alternative is mentioned earlier, which causes a bit of a data leak.

**Comment by se-bastiaan** [comment]
This sounds like a solution to a problem that is caused by something in your process. Why do multiple people have this csv for example? Could we implement something to make this easier? What is the problem with the current output?

Also: Why do you need to write a script that is separate? This sounds like a perfect thing that we could just integrate.

I would personally say that I am against exposing an endpoint that spits out all this member information. Imagine if for some reason our authentication would fail, that'd be an _actual_ data leak (since all the Thabloid members are part of thalia it never leaves the association hence it is not a leak) by exposing all this information to the world wide web.

**Comment by pingiun** [comment]
It seems to me that the board can easily filter out the information that is not needed, and maybe even do the work of printing out the labels so that these files with personal data stay on as few computers as possible. It will likely cost us more time to implement and maintain this feature than for the board to do a little bit of extra work

**Comment by JobDoesburg** [comment]
Discussed it again and there are some important things:


1. Adding this API endpoint is really easy and it really is low-maintainance
2. We do see added value in using an API endpoint in a script to access this member data, over a .csv export that results in files that can keep hanging around in mailboxes or on devices. Yes, people should delete the files, but we also see that people are lazy and don't do that. And having this API endpoint can better prevent this (because for a lot of use cases, there's no need to write the member data to disk).

We might actually remove the .csv export later

**Comment by DeD1rk** [comment]
We now have a view specifically for (a subset of) thabloidcie with only the relevant information. You can download CSV from there, which I think should be fine. If you really think it's easier/better to make a full endpoint for it we can think about that (but you could also just use the CSV export URL in a script), but I don't think it matters much any more. Do you agree @MeItsLars?

**Comment by MeItsLars** [comment]
Yeah, sure!
