### ISSUE TITLE
Validated bootstrap form checkmarks show weirdly for select fields 

### ISSUE THREAD

**Issue by JobDoesburg** [svthalia/concrexit#2602]
### Describe the bug
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/7915741/196044576-39de5c2a-8e79-4b13-85fc-be58f48e04aa.png">

### How to reproduce
Steps to reproduce the behaviour:
1. Save your member profile page, but make one field not validate
2. Profit

### Expected behaviour
A simple single checkmark like for the other fields

### Additional context
This is probably broken site-wide with djangobootstrap forms and our styling in general

**Comment by DeD1rk** [comment]
Adding `background-repeat: no-repeat` in bootstrap solves it: 
<img width="1394" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/68f71a25-62d7-47a1-99d6-86c6f4c9c3ed">

The problem is in this, which overrides the no-repeat originally set by bootstrap: 
<img width="616" alt="afbeelding" src="https://github.com/svthalia/concrexit/assets/41264528/affdec3d-e008-4e7c-bd88-80d64f377715">

I'm having some struggles with compressor so it's hard to test but I'll make a PR once I can test
