### ISSUE TITLE
Newsletter automatic send does not work

### ISSUE THREAD

**Issue by CatoOri** [svthalia/concrexit#2739]
I believe this was briefly fixed, but the newsletter automatic send does not work. 

The newsletter for week 52 was supposed to send December 25 at 20:00:00, but did not send. I removed the send date, so that if you fix it, the email wont be sent out late again.

**Comment by JobDoesburg** [comment]
The problem turns out to be that a little over 1 month ago, something was released that breaks rendering the newsletter, starting a sending job that doesn't stop (so it was still sending a previous newsletter). That's probably because of a bug in the thumb nailing code: https://sentry.io/organizations/thalia/issues/3802668342/?environment=production&project=1463433&query=is%3Aunresolved&referrer=issue-stream

**Comment by DeD1rk** [comment]
@JobDoesburg has this been fixed?

**Comment by DeD1rk** [comment]
I mean based on sentry I guess not but I have received newsletters...

**Comment by JobDoesburg** [comment]
So sending newsletters does work, but I think it is still possible that sending a newsletter can reach this infinite loop thingy, whatever it might exactly be

**Comment by DeD1rk** [comment]
Should be solved with the new thumbnails, and no longer appears in sentry
