### ISSUE TITLE
CMYK colour code styleguide incorrect.

### ISSUE THREAD

**Issue by timkersten655** [svthalia/concrexit#2799]
The CMYK code for Magenta is incorrect on the styleguide. The correct one is 0/85/50/10.

**Comment by timkersten655** [comment]
The CMYK code for black is also wrong. Should be 0/0/0/100.

**Comment by JobDoesburg** [comment]
> The CMYK code for black is also wrong. Should be 0/0/0/100.

I don't think so. 0/0/0/100 is a very basic black color and when actually printing it, it will look flat. The color that is in the style guide is a rich black color. Though I must say the color currently on the site is not a normal rich black color. https://en.m.wikipedia.org/wiki/Rich_black

**Comment by JobDoesburg** [comment]
> The CMYK code for Magenta is incorrect on the styleguide. The correct one is 0/85/50/10. 

This also depends. You should really check out an actual printed document to verify if the color matches. There is no single easy way to convert RGB to CMYK so there is no single 'correct one'.

**Comment by timkersten655** [comment]
> I don't think so. 0/0/0/100 is a very basic black color and when actually printing it, it will look flat. The color that is in the style guide is a rich black color. Though I must say the color currently on the site is not a normal rich black color. https://en.m.wikipedia.org/wiki/Rich_black

Converting the current RGB or HEX code give the CMYK 0/0/0/100. The styleguide should not give different shades of black for different systems.

**Comment by JobDoesburg** [comment]
> Converting the current RGB or HEX code give the CMYK 0/0/0/100. The styleguide should not give different shades of black for different systems.

The point is that RGB and CMYK are different color systems. RGB (and HEX which is basically RGB) is a way of encoding colors that are formed with lightwaves. 

CMYK is a color system based on paint and thus on reflection. You cannot simply give the CMYK color of a RGB color, because it are fundamentally different colors. The way CMYK looks, for example, is highly influenced by the underground that the paint is applied to, and the color of the light source that is reflected / absorbed by the paint.

So, RGB-Thalia-magenta and CMYK-Thalia-magenta are two fundamentally different kinds of colors. The only proper way of converting them is to just visually compare them to each other. And I assume that the committee that created the corporate identity did just that.

The online available tools all use some formula the convert RGB to CMYK, but there is no 'official' or 'correct' way of converting them.
