### ISSUE TITLE
Make facedetection more noticeable

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3427]
### What?

I would like to make it a bit easier to notice that you can use facedetection.

### Why?

Few people are aware of the possibility (e.g. pretty much no sjaars uses it), and it's currently quite far away. Facedetection is a really cool feature, we should flex with it!

### How?

We can promote it a bit. Some ideas: 
- We could put a link to 'your photos' in the user menu dropdown.
- We can display a banner for people who don't have reference faces set up (although perhaps we shouldn't keep bothering users who simply choose not to use it, e.g. for privacy reasons).
- We can show some banners on specific pages only: e.g., a large obvious banner on the albums/photos pages for users who don't have reference faces yet.
- We can also do some temporary advertisement of course: request a website slide from promocie, a note in a newsletter some day from @JeeVee11, etc.

**Comment by W-M-T** [comment]
Some comments as an active member that isn't using the feature:
One of the reasons that I don't use it is because I'm not informed how well it works, it feels like the kind of feature that is easily introduced but more difficult to have it be of additive value.
W.r.t. privacy: even though you state in the privacy policy that face detection is done only on your own servers, this isn't shown on the page https://thalia.nu/members/photos/facedetection/reference-faces/, so you will only find that out if you explicitly read the privacy policy.
Lastly: having to go out of your way to take and upload reference faces, which then take some unspecified time to be verified, feels kind of like a hassle for a feature that, if it works well (which you don't know ahead of time), makes you go "hey that's pretty cool". Not sure how that barrier can be lowered. I understand that the verification part is there for a reason, so I wouldn't want to get rid of that.

**Comment by Scarletto** [comment]
TODO:
Include link to face detection menu in Profile dropdown.
Put banner on photo page for un-set face detection.
Delete text from photo page, extend search bar to whole screen, change "search" to spyglass, add text to liked and face detection buttons.

**Comment by Scarletto** [comment]
Instead of a banner, I now made the button stand out more if face-detection is not yet enabled. This is in my opinion a sleeker, less "invasive" way of doing it. Is this OK?
![image](https://github.com/svthalia/concrexit/assets/24889701/fdd5c12f-ea68-4623-9825-b4e63b661c61)
