### ISSUE TITLE
oldmembers mailinglist incomplete

### ISSUE THREAD

**Issue by ColonelPhantom** [svthalia/concrexit#3435]
### Describe the bug
The oldmembers mailinglist is incomplete, and some past members are not on the list.

Specifically, the member in question who sent us an email seems to have his old membership listed in the database as a benefactorship. We should probably investigate why that is and how to fix these memberships, or at least work around the problem.

**Comment by JobDoesburg** [comment]
Well, if someone has always been benefactor and never been a member, this is just working as intended

**Comment by ColonelPhantom** [comment]
Correct, but apparently some former members are incorrectly listed in the database as former benefactors instead. We received an email documenting at least one such case, he was a member from 2010-2015 and a benefactor for some years after that, but the current database has him listed only as past benefactor.

Likely something happened during the migration to concrete5 or Django that lost this information (?).

**Comment by DeD1rk** [comment]
It seeems that indeed many memberships haven't been migrated (or perhaps never stored at all). But not _all_ really old memberships...

**Comment by DeD1rk** [comment]
For example, we have these: ```
member 2008-09-01 2013-08-31
member 2008-09-12 2018-09-01
honorary 2008-09-22 None
member 2009-05-14 2018-09-01
benefactor 2009-08-17 2017-09-01
```

So that's both things ending before concrete5 and things starting before concrete5 and ending in django, and of all types. So I don't really see a pattern that would explain a 2015-2020 thing missing?

Perhaps we've only migrated (or perhaps ever stored) the 'latest' membership at that time?

There are also many members for whom we have _no_ memberships.

**Comment by DeD1rk** [comment]
Perhaps we can find out how it is in https://github.com/svthalia/concrete5-website, or in some of the first commits in this repo? But I'm not sure if it's really worth trying to restore old memberships. I would prefer having missing memberships over incorrect ones from a privacy perspective. And even _trying to restore_ memberships would kind of be actively gathering data on people who really no longer have anything to do with us.

**Comment by JobDoesburg** [comment]
Maybe it is better to create the mailing list fully based on the 'receive alumni emails' field in the profile. 

And hide that field from a user's profile when it's false and the user has no memberships / or only benefactor memberships. 

And for one time, set the field to true for all people from before concrexit

**Comment by DeD1rk** [comment]
> And hide that field from a user's profile when it's false and the user has no memberships / or only benefactor memberships.

That sounds confusing. People should be able to indicate that they don't want the emails at any time, and also be able to get them again if they ever want to (it may be unlikely that that ever happens but I don't think unsubscribing should be 'destructive', even if only for those users we don't have a member-membership of).

**Comment by JobDoesburg** [comment]
Yeah okay that's not what I meant. I mean that we shouldn't have too much logic in the mailing list, and just base it on a boolean field that admins can override as well.

And then write some logic to set the boolean field to true for the right people (and prevent that people that haven't been a member ever, or are still studying, can't get in the list)

**Comment by joostrijneveld** [comment]
> Likely something happened during the migration to concrete5 or Django that lost this information (?).

While that was also my initial thought, the [time of implementation](https://github.com/svthalia/concrexit/commit/6e1495a76f241dc1a7767514d14bd78068a46efc) of the memberships in Django suggests that the memberships (or, more specifically: at least _my_ membership) [were likely successfully migrated](https://github.com/svthalia/concrexit/commit/3910ae3f58930c48c636512afe12de5735c2e35d); I feel like I would've noticed in 2016 or 2017, otherwise..

Perhaps the bug lies in the off-boarding of members (i.e. the process of changing a member into a benefactor). If this is a manual process in the Django admin interface (which I'm assuming it may be), perhaps the secretary performing this change in membership _updated_ the membership object rather than _added_ a new membership with type 'benefactor'. It seems unlikely that this is an automatic process, since that would require knowing when lifetime-members graduate.. That make sense with regards to my personal timeline; I would assume I would've been changed to a benefactor as of september 2015 rather than 2017.

Alternatively, perhaps a database migration (i.e., when a model was changed) introduced a bug that destroyed historical memberships (but scrolling through the migrations does not immediately lead to anything). It would be interesting to find out the scale of the impacted memberships (i.e., when do we see the errors? does that involve people who became benefactor at a certain date / specific year)?

In any case, I'm assuming no backups are available that date back sufficiently far enough that still include the undamaged memberships. Happy to be proven wrong 😄

**Comment by DeD1rk** [comment]
> I'm assuming no backups are available that date back sufficiently far enough 

That's correct.

From the migrations, it makes sense that we don't have a membership history for anyone from before django, except some cases that were manually changed. Indeed your specific case must have been manually editted (incorrectly), because we only migrated memberships in 2016-2017.

Ending study-time memberships is (at least until now) a manual process by the secretary, so it's not unlikely that some memberships may have had their types changed, or even been deleted.
I find a bug having caused this quite unlikely.

Anyway, regardless of how your and other memberships have ended up being inaccurate, there is mainly a large number of users for whom we don't have any memberships at all (I assume this is exactly the users of concrete5 who did not have a membership any more at the time of the migration. Most of these should also be counted as alumni.


A good solution might be roughly what @JobDoesburg suggested to change how the oldmembers list is made to:
- Users can set a field (prefereably with a proxy/separate 'MailinglistsUser' model approach like a la #2630, also with an eye on #2492) on their profile (and probably somewhere else for #3378).
- People are added on the mailinglist iff they have that field set, and they don't have a current member membership.
- We disable turning that field on for people who haven't had a member membership.

We can then send a one-time email to everyone we know who isn't currently a member and isn't on the oldmembers list yet, offering to add them (for all I care by replying or a temporary google form; I can then just enter a CSV of users at once from the shell), bypassing that they can't enable the field themselves.

That way we can have old-old oldmembers (who as far as we know never had a membership) and people who 'have only been benefactors' still get on the list as a one-time thing. Once they unsubscribe, they would only be able to resubscribe through an admin (we should show a hint for that to users for who the field is disabled). 

@ricotewechel does that sound like a good solution?

**Comment by DeD1rk** [comment]
Note, there are 1073 (!!) users with no membership at all, all of which would have to get that email. That's a lot of people. On the other hand, the vast majority of those 'should' be on the oldmembers list (of 955 people right now), so we are missing _a lot_ of alumni without doing it.

It's also possible to add all of them without them actively subscribing of course, but there would be a number (100? 300?) of people who aren't actually alumni. So then unsubscribing should just be really easy for them.

**Comment by ricotewechel** [comment]
> A good solution might be roughly what @JobDoesburg suggested to change how the oldmembers list is made to:
> 
> * Users can set a field (prefereably with a proxy/separate 'MailinglistsUser' model approach like a la [Proxy models and admin views for giving certain committees / apps access to certain parts of members database #2630](https://github.com/svthalia/concrexit/issues/2630), also with an eye on [Manage mailing list moderators via concrexit #2492](https://github.com/svthalia/concrexit/issues/2492)) on their profile (and probably somewhere else for [Opt-out from alumni newsletter not possible without filling in many account details #3378](https://github.com/svthalia/concrexit/issues/3378)).
> * People are added on the mailinglist iff they have that field set, and they don't have a current member membership.
> * We disable turning that field on for people who haven't had a member membership.

@DeD1rk this proposed solution sounds perfect for a general policy for accounts from now on. Just to double check: The moment the secretary ends your member-membership by setting an end date, the field should be set to true, right? This makes the list opt-out.

> We can then send a one-time email to everyone we know who isn't currently a member and isn't on the oldmembers list yet, offering to add them (for all I care by replying or a temporary google form; I can then just enter a CSV of users at once from the shell), bypassing that they can't enable the field themselves.

I am more in favor though of adding all of the mail addresses to the mailing list without having them actively subscribe, like you mention in your last comment. I think this won't be an issue since those not interested will unsubscribe anyway, and the newsletter is only sent like 2 or 3 times a year. It will really help the alumnicie, though. By the time I send the next alumni newsletter (probably end of 2023) I can make sure to add an explanation together with you on how to unsubscribe.

Does that sound feasible?

Also thanks @joostrijneveld for thinking with us here

**Comment by DeD1rk** [comment]
> by setting an end date, the field should be set to true, right?

I guess we would set the field true for all new and existing users (so also for all current members, you should also be able to opt-out _before_ becoming alumnus I think), except new users from a benefactor registration? Implementation needs some more thinking through. (See below, I think this is a pretty simple fix)



<details>
  <summary>My detailed design thinking out loud</summary>
  
  We should probably not implement a proxy model for this now, as that complicates things further.
  
  - We keep the existing `Profile.receive_oldmembers`
  - When creating a new benefactor, we set the field to False explicitly.
  - For other new members, we set the field True (the default).
  - It is currently already True for basically everyone.
  - We need to set it to False one time for:
    - Current benefactors created starting from september 2017 (whose membership history we most likely have correct)
    
  - The field can be changed unless its value is currently False, and the user has never had a Member membership. If the field is disabled, we show an instruction that they can contact info@thalia to get subscribed.
    
  - People are on the list if they have the field set, and they don't have a current Member membership.

  So the changes we'd need are: 
  1. When creating a benefactor from a registration, set `Profile.receive_oldmembers=False`.
  2. Disable the field in profile when it's False and the user hasn't been Member (and explain why).
  3. Build the mailinglist based on only `Profile.receive_oldmembers & not current Member`.
  4. Migration to set the field False for post-2016-2017 benefactors.
  And of course we need to have tackled #3378. 
  
</details>
