### ISSUE TITLE
EventRegistrations not linked in MoneyBird

### ISSUE THREAD

**Issue by BigRoelof** [svthalia/concrexit#3502]
### Describe the bug
In MoneyBird, a large amount of registrations for the Sinterklaas Cantus dit not have an external invoice created for them. Only me Jord and Joris (who all were registered through the back-end before registrations were open) had an external invoice. This also occured to the registrations of the Drink and Drive event. The problem happens for pin registrations as well as TPay registrations.

### How to reproduce

1. Log in to 'MoneyBird'
2. Click on 'Bank -> 'Pin (CCV)' or 'ThaliaPay (concrexit)'
3. Scroll down to 'the transactions from the Sinterklaas cantus'

**Comment by DeD1rk** [comment]
I tried running https://github.com/svthalia/concrexit/blob/c1d1827533d816bdc4f1ccb9c9d2bfeec632e3e2/website/moneybirdsynchronization/services.py#L367 in the shell on production, and it does have return a bunch of registrations (I pushed all 72 right now). So for some reaon they aren't getting pushed. But from the logs, https://github.com/svthalia/concrexit/blob/c1d1827533d816bdc4f1ccb9c9d2bfeec632e3e2/website/moneybirdsynchronization/services.py#L407 is being run, so it's not because of it crashing on some unhandled exception.
