### ISSUE TITLE
RFC: randomize event registration admission

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3524]
### What?
We could change event registrations such that a random pick of event registrations made within the first X minutes of the registration period opening are admitted. For example, during the first 5 minutes of an event opening, people can make registration. After those 5 minutes, the max number of participants are selected randomly from those registrations, and only then, a confirmation email is sent to everyone and people show up on the participant list.

### Why?
This could be considered more fair (no advantage to be gained by using the API directly or depending on your internet speed). It may also reduce the peak load on our servers.

### How?
This is a bit of a complicated question. We could give registrations an explicit status field like `invited`, `queued`, `cancelled` (or emulate something like that by among others making `queue_position` a field in the db).

**Comment by ColonelPhantom** [comment]
I'm not the biggest fan of this idea personally, since we already have #3522 which should negate any fairness issues apart from internet speed. Although that last reason does probably have some appeal.

If we want to implement this, I would propose simply setting a constant amount of time (via settings), although we could also add it as an event field. We should then be able to detect a 'pending' registration via the centralized event status logic. Then, at 'finalization' time we can just overwrite the registration times depending on the order.

Overwriting the registration times sounds a bit ugly, but has the advantage that we don't need to change any of our existing logic that deals with registration order.

Implementing it with a new field (although that's not a `queue_position` but just a `position`) in the registration would also work, and we just set that to `None`/`NULL` before the confirmation, and set it to the shuffled order after, and later registrations just get max+1. But I'm kinda worried if we maybe do a bunch of `order_by('date')` which would then break.

**Comment by DeD1rk** [comment]
Since we don't have peak load issues after our recent optimizations and by scaling up when a large event is coming, I guess we can really reject this idea for now and the coming years. 

Storing the position in the db could have some real performance benefits, but let's not overhaul something really complicated that works well right now.
