### ISSUE TITLE
Promotion requests - two weeks into future

### ISSUE THREAD

**Issue by WidadMajdoubi24** [svthalia/concrexit#3529]
### What?

We want promotion requests to only be possible for two weeks into the future from the date it is being requested. (Except for push notifications, since these do not require design)

### Why?

The promocie has been struggling for quite a while with people requesting things just too last minute. Communication about this just gets lost and people forget. It is really annoying for the committee to last minute rapidly design something. So to prevent this from happening anymore we want it to be only possible to request it for a date two weeks after the date of request or later. 

(promo_publish >= date_of_request + 2 weeks)

### How?

By not letting people select a publish date before that.

**Comment by DeD1rk** [comment]
Note: the validation needs to be only in the eventadmin inline form, not model-wide

**Comment by ColonelPhantom** [comment]
It seems this already happens, except only one week ahead. Additionally, there is a bug that means that putting it on "today" is possible, as this is the default value for some reason (although I hope nobody actually uses this).

I will change the code to require two weeks of notice instead of 1. Should I also change/remove the default value, so that the field is by default empty, or that it has the date of two weeks in the future by default?
