### ISSUE TITLE
Moving Trust contact persons

### ISSUE THREAD

**Issue by HetJoch** [svthalia/concrexit#3562]
### Describe the bug
The trust contact persons tab is under education 

### How to reproduce

1. Go to education
2. Click on trust contact persons
5. See error

### Expected behaviour
I want it to be under "For members"

### Additional context
Please move the TCP tab to the "for members section" instead of the "education" tab

**Comment by T8902** [comment]
I would propose making "Contact" a drop-down menu instead since putting it under for members makes it seem that the trust contact person is only for Thalia members which isn't the case. Otherwise the "Education" dropdown menu would still have my preference since "Association" would relate it too much as being part of thalia which it shouldn't be and "Career" is as unlikely if not more unlikely as "Education" thus I think either change the "Contact' tab in the menu or keep it as is. What do you think @DeD1rk

**Comment by DeD1rk** [comment]
Definitely shouldn't be under 'for members' as TCPs are a non-thalia thing. I don't really see any reason for moving it, as education is where I would expect people to look if they want anything 'serious' or uni-related. It can be moved to contact of course but that suggests that TCPs are a contact-point for thalia, which they are not (and it makes the real contact page a click further away). @HetJoch any motivation for moving it?

**Comment by mark-boute** [comment]
Renaming 'EDUCATION' to 'FOR STUDENTS' might indicate that it's student resources rather than just educational material which might help.

**Comment by DeD1rk** [comment]
For achieving the actual goal of making people _who are not looking for it_ find university resources, a banner would probably be best. Moving the link to the page to somewhere else won't cause people to all of a sudden notice it, while people looking for it specifically are already able to find it.

**Comment by DeD1rk** [comment]
@HetJoch I'll request a banner from promocie: https://thalia.nu/admin/promotion/promotionrequest/373/change/

**Comment by WidadMajdoubi24** [comment]
We think a banner is fine, but the moving of the TCPs on the site does seem impractical, so lets keep it at that.

**Comment by DeD1rk** [comment]
Alright. The banner should be covered by the promorequest, so I'll close this here.
