### ISSUE TITLE
Moneybird contacts are not made for alumni people

### ISSUE THREAD

**Issue by T8902** [svthalia/concrexit#3603]
### Describe the bug

People who are alumni don't have a membership anymore even if they still have an account and thus don't get a moneybird contact which is bad.

### Expected behaviour

If someone has an account and makes a payment at a thalia event, they should get a moneybird contact.

**Comment by DeD1rk** [comment]
I discussed with Roel that we can go with an easier/cleaner solution: when a payer exists for an invoice, but we don't have a moneybirdcontact for whatever reason, we can just fall back to using the unknown payer contact id, like we do for invoices without a payer set at all. 
The project then remains the same, so as far as I know this doesn't really matter for the bookkeeping.

This is more robust and clean because:
- it also works if we somehow can't succeed in making a contact
- it means we don't run into trouble when creating a contact of a minimized profile (which has no address etc.)
- it also means we don't have to make the logic to determine which contacts can be deleted/archived more complex, and don't have to decide on the privacy implications of having contacts of non-members in the site.

@nvoers just to be sure, what do you think about this?
