### ISSUE TITLE
Thesis/internship list

### ISSUE THREAD

**Issue by DeD1rk** [svthalia/concrexit#3706]
### What?
@Sophie2104 and @NotAtec came with the idea to provide a way for iCIS to show a list of thesis and research internship projects on Thalia's site. 

### Why?
This would be a more accessible and uniform alternative to the current practice where each research institute (and several professors) maintain their own list of project ideas. For example: 

- https://www.mbsd.cs.ru.nl/Teaching
- https://www.cs.ru.nl/~jhh/education.html

The hope is mainly that it is easier for students to find this on thalia.nu than when spread out accross multiple sites.

Additionally, through some moderation by educacie perhaps the list could be kept up to date more. For example, educacie could maybe proactively periodically reach out to professors, which as a professor could be a more low-effort way of publishing your ideas.

I do think this needs to be fleshed out a bit more. If we implement this it requires:

- Long-term commitment from educacie to maintain the list.
- Cooperation from the majority of professors and institutes: there's no point in doing this if the professors and institutes don't like to use it, and decide to keep their own lists. 
- It would be nice if institutes link to us once it's working. For example, there's this page https://www.ru.nl/en/institute-for-computing-and-information-sciences/education/master-thesis-lab that has _dead_ links to institute pages.
- It should be publicly visible.

### How?
Add a simple model for a project, and some possibilities for tagging them, linking to a contact person or external pages. Initially, I think it would make sense if projects can only be created from the admin by educacie. 

In the long term, we could consider adding a public form that iCIS staff (actually everyone) can use to submit proposals for review by educacie. But that could be prone to spam. Alternatively, we could limit that to logged in users (such as iCIS benefactors). But that does not include many professors and requires them to have their login credentials ready, so doesn't really work to make it effortless for staff to submit projects.

**Comment by DeD1rk** [comment]
@Sophie2104 @NotAtec maybe it would be good to work out this idea a bit more also within educacie, and discuss it with iCIS or reach out to some individual professors to get their opinion. Their support really is crucial for this idea to work out so we should investigate that before committing to it.

**Comment by NotAtec** [comment]
I think it's best if we first see if we can get some people within Thalia (Probably educacie) to keep this updated. I can get started contacting the relevant people to see if we can get support for this before we start building it into the site.

@rutgerbrf tagging you so you know what i'm on about once i msg you :)

**Comment by DeD1rk** [comment]
bump @NotAtec any updates?

**Comment by NotAtec** [comment]
Yeah i discussed it with both Felipe and iCIS / Educacie, and the conclusion seems to be that it's not worth it to spend much effort on this. From Felipe i heard there's already a page companies use to publish vacant internships (As a filter on the vacancies page https://thalia.nu/career/vacancies#)

From iCIS I unfotunately got a reply stating that there's no interest from them in helping us maintain this list. Reason stated was that it's already too fragmented and that they expect it to be impossible to actually keep one single list updated. An idea stated by Peter Achten was that instead of aggregating the internships ourselves, we could link to the relevant pages by the institute or teachers who maintain their own list.

Maybe we could look at creating such an aggregation list, because it would make gathering ideas a little easier. However we should also ask the question if it's worth it to maintain a page that's effectively just links to other (Usually pretty out of date anyways) pages.
@DeD1rk what do you think of the above? Otherwise we can probably close this and just keep it at the vacancies page (Or maybe move that internships list around a bit to make it easier to find?)

**Comment by DeD1rk** [comment]
> there's no interest from them in helping us maintain this list

That's sad, but not entirely unexpected. I think we all already knew that it's currently too fragmented - that's the entire reason to implement this - but if they don't want to cooperate on a solution then indeed it won't work.

I agree making a list of links to lists is better than nothing, but indeed, that list itself would probably just get outdated. 

So I guess sadly we can just close this.

@everyone feel free to comment or reopen if you have any ideas :)
