### ISSUE TITLE
vacancy API is completely broken

### ISSUE THREAD

**Issue by JAicewizard** [svthalia/concrexit#3858]
### Describe the bug
The company name is not accurate at all

### How to reproduce

1. Go to https://staging.thalia.nu/api/v2/partners/vacancies/?limit=1000&offset=0
2. See most vacancies having incorrect company name

### Expected behaviour
Company name should be accurate

**Comment by JAicewizard** [comment]
Same for company logo

**Comment by DeD1rk** [comment]
Vage shit

**Comment by ColonelPhantom** [comment]
The main problem seems to be that only external vacancies (vacancies from non-partners) get the `company_name` etc fields filled out.

'Internal' vacancies (from partners) only get the partner id, but not any actually useful info. We should, at the very least, inline the information about each partner into the response instead of just giving an id. If we don't do that, we would force the app to perform `n+1` requests, which is obviously a Bad Idea™️.

We could do more, but I think in the website we mostly work with `if partner then partner.name else company_name`-like logic, and it does make a difference, e.g. the 'more info' link goes to the partner page if the vacancy is 'internal' and otherwise it scrolls down to the list of all vacancies (although we may want to redesign that? it doesn't seem to contain any info that's not up top, so putting the external link directly might be better).
